import { type Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignIn,
  SignOutButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import '../app/globals.css';
import ContextProvider from '../context/ContextProvider';
import type { ReactNode } from 'react';
import UserStatus from '../components/UserStatus';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body 
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <UserStatus />
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
              <SignOutButton>
                <button 
                suppressHydrationWarning={true}
                className="ml-2 bg-red-500 text-white rounded-full px-4 py-2 text-sm">
                  Log Out
                </button>
              </SignOutButton>
            </SignedIn>
          </header>
          <SignedIn>
            <ContextProvider>{children}</ContextProvider>
          </SignedIn>
          <SignedOut>
            <div className="min-h-screen flex items-center justify-center">
              <SignIn />
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
